version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.10.79:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Postgresql Database
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mancala_db
      POSTGRES_USER: bol_user
      POSTGRES_PASSWORD: bol_password
    ports:
      - "5432:5432"  # Expose Postgresql port

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      KEYCLOAK_ADMIN: bol_admin
      KEYCLOAK_ADMIN_PASSWORD: bol_password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/mancala_db
      KC_DB_USERNAME: bol_user
      KC_DB_PASSWORD: bol_password
      KC_METRICS_ENABLED: false
    volumes:
      - ./keycloak/import-data:/opt/keycloak/data/import
    command: ["start-dev", "--import-realm"]
    ports:
      - "8080:8080"  # Expose Keycloak port
    depends_on:
      - postgres


  # Eureka Service Registry
  eureka:
    build:
      context: ./eureka  # Directory containing the Eureka service Dockerfile
    ports:
      - "8761:8761"  # Expose Eureka port

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway  # Directory containing the API Gateway Dockerfile
    ports:
      - "7070:7070"  # Expose API Gateway port
    depends_on:
      - eureka  # Ensure API Gateway starts after Eureka
      - keycloak
    environment:
      KEYCLOAK_BASE_URL: http://keycloak:8080
      CLIENT_ID: mancala_rest_api
      EUREKA_DEFAULT-ZONE: http://eureka:8761/eureka

  # Mancala Service
  mancala-service:
    build:
      context: ./mancala-service  # Directory containing the Mancala Service Dockerfile
    ports:
      - "8081:8081"  # Expose Mancala Service port
    depends_on:
      - eureka
      - postgres
    environment:
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://eureka:8761/eureka
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/mancala_db
      DATASOURCE_USERNAME: bol_user
      DATASOURCE_PASSWORD: bol_password
      SERVER_PORT: 8081


  #Angular App
  angular-app:
    build:
      context: ./angular-app # Directory containing the angular-app Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - keycloak

