mancala:
  keycloak-base: ${KEYCLOAK_BASE_URL:http://192.168.10.79:8080}
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - RewritePath=/api/v1/.*?/(?<remaining>.*), /$\{remaining}
      routes:
        - id: mancala-service
          uri: lb://mancala-service
          predicates:
            - Path=/api/v1/mancala/**
        - id: waiting-room
          uri: lb://waiting-room
          predicates:
            - Path=/api/v1/waiting-room/**
      discovery:
        locator:
          enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:${mancala.keycloak-base}/realms/mancala/protocol/openid-connect/certs}
      client:
        provider:
          keycloak:
            authorization-uri: ${AUTH-URI:${mancala.keycloak-base}/realms/master/protocol/openid-connect/auth}
            user-info-uri: ${USER_INFO:${mancala.keycloak-base}/realms/master/protocol/openid-connect/userinfo}
            jwk-set-uri: ${JWK_SET_URI:${mancala.keycloak-base}/realms/master/protocol/openid-connect/certs}
            token-uri: ${TOKEN-URI:${mancala.keycloak-base}/realms/mancala/protocol/openid-connect/token}
        registration:
          keycloak:
            client-id: ${CLIENT_ID:mancala_rest_api}
            authorization-grant-type: password
            scope: openid
            redirect-uri: ${REDIRECT-URL:http://localhost:4200}
            client-authentication-method: post
server:
  port: 7070
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT-ZONE:http://localhost:8761/eureka/}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG