spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: mancala-service
          uri: lb://mancala-service
          predicates:
            - Path=/mancala-service/**
          filters:
            - RewritePath=/mancala-service/(?<remaining>.*), /$\{remaining}
      discovery:
        locator:
          enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7070/realms/mancala
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
