# syntax=docker/dockerfile:1.4

#Building Angular app
#Latest Node that work with Angular CLI 16.2.9
FROM node:18.18.2-slim

#Create project Folder and Copy angular files into it
RUN mkdir /project
WORKDIR /project
RUN mkdir /src
COPY *.json ./
COPY ./src ./src


# Install Angular CLI globally
RUN npm install -g @angular/cli@16.2.9

# Load and Install all necessary modules
RUN npm ci

# Build Angular app
CMD ng serve --disable-host-check --host 0.0.0.0