eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT-ZONE:http://localhost:8761/eureka/}
server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: mancala-service
  sql:
    init:
      mode: always
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/mancala_db}
    username: ${DATASOURCE_USERNAME:bol_user}
    password: ${DATASOURCE_PASSWORD:bol_password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop